# Generated by Django 4.0.6 on 2022-07-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetails',
            name='Hlevel',
            field=models.IntegerField(default=0),
        ),
    ]
