# Generated by Django 4.0.6 on 2022-07-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_fooddetails_hlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetails',
            name='Date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='Email',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='Fexpiry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='Mobileno',
            field=models.IntegerField(default=0),
        ),
    ]
