# Generated by Django 4.0.6 on 2022-07-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_fooddetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddetails',
            name='Fexpiry',
            field=models.IntegerField(default=0),
        ),
    ]
