# Generated by Django 4.0.6 on 2022-07-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_fooddetails_fexpiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddetails',
            name='Date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='Fexpiry',
            field=models.TimeField(default=0),
        ),
    ]
