# Generated by Django 4.0.6 on 2022-07-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_remove_fooddetails_date_remove_fooddetails_fexpiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetails',
            name='Date',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='Fexpiry',
            field=models.TimeField(default=0),
        ),
    ]
