# Generated by Django 4.0.6 on 2022-07-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_fooddetails_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
