# Generated by Django 4.0.6 on 2022-07-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddetails',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='fooddetails',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='fooddetails',
            name='Fexpiry',
        ),
        migrations.RemoveField(
            model_name='fooddetails',
            name='Mobileno',
        ),
    ]
