# Generated by Django 4.0.6 on 2022-07-15 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_remove_fooddetails_date_remove_fooddetails_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetails',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='Email',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='Fexpiry',
            field=models.TimeField(default=0),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='Mobileno',
            field=models.IntegerField(default=0),
        ),
    ]
